import { useState } from 'react';
import { ArrowLeft, ChevronRight, MoreHorizontal, UserPlus, Star, Ban, Trash2, Home, BookOpen, FileText, Brain, ImagePlus, Upload, Link2, X as XIcon, List } from 'lucide-react';
import { Avatar, AvatarImage, AvatarFallback } from './ui/avatar';
import { ScrollArea } from './ui/scroll-area';
import { Button } from './ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from './ui/dialog';
import { Switch } from './ui/switch';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from './ui/alert-dialog';
import { toast } from 'sonner@2.0.3';
import { Contact, AvatarItem } from './Contacts';
import { WorldBook } from './WorldBookManager';
import { Rule } from './RulesManager';
import { MomentPost } from './Moments';
import { Input } from './ui/input';
import { Label } from './ui/label';
import { Checkbox } from './ui/checkbox';
import { Textarea } from './ui/textarea';
import { ImageWithFallback } from './figma/ImageWithFallback';

interface GroupInfo {
  id: string;
  name: string;
}

interface ContactProfileProps {
  contact: Contact;
  onClose: () => void;
  wechatId?: string; // 微信号（可选）
  region?: string; // 地区（可选）
  onSendMessage?: () => void; // 点击发消息按钮的回调
  onVideoCall?: () => void; // 点击视频通话按钮的回调
  commonGroups?: GroupInfo[]; // 共同群聊
  signature?: string; // 个性签名
  onContactUpdate?: (contact: Contact) => void; // 更新联系人信息的回调
  onContactDelete?: (contactId: string) => void; // 删除联系人的回调
  worldBooks?: WorldBook[]; // 所有可用的世界书
  rules?: Rule[]; // 所有可用的规则
  moments?: MomentPost[]; // 所有朋友圈数据
  onMomentsClick?: () => void; // 点击朋友圈查看更多的回调
  summaries?: { id: string; timestamp: number; content: string; isAutoGenerated: boolean }[]; // 角色总结
}

export function ContactProfile({ contact, onClose, wechatId, region, onSendMessage, onVideoCall, commonGroups = [], signature, onContactUpdate, onContactDelete, worldBooks = [], rules = [], moments = [], onMomentsClick, summaries = [] }: ContactProfileProps) {
  const [showProfileDetail, setShowProfileDetail] = useState(false);
  const [showSettingsPage, setShowSettingsPage] = useState(false);
  const [showDeleteDialog, setShowDeleteDialog] = useState(false);
  const [showAiSettings, setShowAiSettings] = useState(false);
  const [isStarred, setIsStarred] = useState(contact.isStarred || false);
  const [isBlacklisted, setIsBlacklisted] = useState(contact.isBlacklisted || false);
  
  // AI设置状态
  const [contextMemoryCount, setContextMemoryCount] = useState(contact.contextMemoryCount || 10);
  const [selectedWorldBooks, setSelectedWorldBooks] = useState<string[]>(contact.worldBooks || []);
  const [selectedRules, setSelectedRules] = useState<string[]>(contact.rules || []);
  
  // 头像库相关状态
  const [showAvatarLibrary, setShowAvatarLibrary] = useState(false);
  const [showAddAvatar, setShowAddAvatar] = useState(false);
  const [avatarLibrary, setAvatarLibrary] = useState<AvatarItem[]>(contact.avatarLibrary || []);
  const [newAvatar, setNewAvatar] = useState({ url: '', emotion: '', description: '' });
  const [avatarUploadMethod, setAvatarUploadMethod] = useState<'url' | 'upload'>('url');
  const [avatarLocalFile, setAvatarLocalFile] = useState<File | null>(null);
  const [avatarLocalPreview, setAvatarLocalPreview] = useState<string>('');
  const avatarFileInputRef = useState<HTMLInputElement | null>(null)[0];
  
  const formatTime = (timestamp: number) => {
    const now = Date.now();
    const diff = now - timestamp;
    const days = Math.floor(diff / 86400000);
    
    if (days === 0) return '今天';
    if (days === 1) return '昨天';
    if (days < 7) return `${days}天前`;
    
    const date = new Date(timestamp);
    return `${date.getMonth() + 1}月${date.getDate()}日`;
  };

  // 处理星标朋友切换
  const handleStarToggle = (checked: boolean) => {
    setIsStarred(checked);
    if (onContactUpdate) {
      onContactUpdate({ ...contact, isStarred: checked });
    }
    toast.success(checked ? '已设为星标朋友' : '已取消星标朋友');
  };

  // 处理黑名单切换
  const handleBlacklistToggle = (checked: boolean) => {
    setIsBlacklisted(checked);
    if (onContactUpdate) {
      onContactUpdate({ ...contact, isBlacklisted: checked });
    }
    toast.success(checked ? '已加入黑名单' : '已移出黑名单');
  };

  // 处理删除好友
  const handleDeleteContact = () => {
    if (onContactDelete) {
      onContactDelete(contact.id);
      toast.success('已删除好友');
      onClose();
    }
    setShowDeleteDialog(false);
  };

  // 处理推荐给朋友
  const handleRecommend = () => {
    toast.success('推荐功能开发中');
  };

  // 处理添加到桌面
  const handleAddToHome = () => {
    toast.success('已添加到桌面');
  };

  // 处理头像本地文件上传
  const handleAvatarFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    if (!file.type.startsWith('image/')) {
      toast.error('请选择图片文件');
      return;
    }

    if (file.size > 5 * 1024 * 1024) {
      toast.error('图片大小不能超过5MB');
      return;
    }

    setAvatarLocalFile(file);

    const reader = new FileReader();
    reader.onload = (event) => {
      if (event.target?.result) {
        setAvatarLocalPreview(event.target.result as string);
        setNewAvatar({ ...newAvatar, url: event.target.result as string });
      }
    };
    reader.readAsDataURL(file);
  };

  // 添加头像到库
  const handleAddAvatarToLibrary = () => {
    if (!newAvatar.url.trim()) {
      toast.error('请输入头像URL或上传图片');
      return;
    }
    if (!newAvatar.emotion.trim()) {
      toast.error('请输入情绪/场景标签');
      return;
    }
    if (!newAvatar.description.trim()) {
      toast.error('请输入描述');
      return;
    }

    const newAvatarItem: AvatarItem = {
      id: Date.now().toString(),
      url: newAvatar.url.trim(),
      emotion: newAvatar.emotion.trim(),
      description: newAvatar.description.trim(),
    };

    setAvatarLibrary([...avatarLibrary, newAvatarItem]);
    toast.success('头像已添加');
    
    // 重置表单
    setNewAvatar({ url: '', emotion: '', description: '' });
    setAvatarLocalFile(null);
    setAvatarLocalPreview('');
    setShowAddAvatar(false);
  };

  // 删除头像
  const handleDeleteAvatar = (id: string) => {
    setAvatarLibrary(avatarLibrary.filter(a => a.id !== id));
    toast.success('头像已删除');
  };

  // 保存头像库
  const handleSaveAvatarLibrary = () => {
    if (onContactUpdate) {
      onContactUpdate({
        ...contact,
        avatarLibrary
      });
    }
    toast.success('头像库已保存');
    setShowAvatarLibrary(false);
  };
  
  // 如果显示设置页面
  if (showSettingsPage) {
    return (
      <div className="fixed inset-0 bg-[#EDEDED] z-[70] flex flex-col">
        {/* 顶部导航栏 */}
        <div className="flex items-center justify-between px-4 py-3 bg-[#F7F7F7] border-b border-gray-200">
          <button
            onClick={() => setShowSettingsPage(false)}
            className="p-2 hover:bg-gray-200 rounded-full transition-colors -ml-2"
          >
            <ArrowLeft className="w-5 h-5" />
          </button>
          <h1 className="absolute left-1/2 -translate-x-1/2">设置</h1>
          <div className="w-9"></div>
        </div>

        {/* 设置选项 */}
        <ScrollArea className="flex-1">
          {/* 第一组 */}
          <div className="mt-3 bg-white">
            <button
              onClick={handleRecommend}
              className="w-full px-4 py-3 flex items-center justify-between hover:bg-gray-50 transition-colors border-b border-gray-100"
            >
              <span>把他（她）推荐给朋友</span>
              <ChevronRight className="w-4 h-4 text-gray-400" />
            </button>

            <button
              onClick={handleAddToHome}
              className="w-full px-4 py-3 flex items-center justify-between hover:bg-gray-50 transition-colors"
            >
              <span>添加到桌面</span>
              <ChevronRight className="w-4 h-4 text-gray-400" />
            </button>
          </div>

          {/* 第二组 */}
          <div className="mt-3 bg-white">
            <div className="px-4 py-3 flex items-center justify-between border-b border-gray-100">
              <span>设为星标朋友</span>
              <Switch
                checked={isStarred}
                onCheckedChange={handleStarToggle}
              />
            </div>

            <div className="px-4 py-3 flex items-center justify-between">
              <span>加入黑名单</span>
              <Switch
                checked={isBlacklisted}
                onCheckedChange={handleBlacklistToggle}
              />
            </div>
          </div>

          {/* 删除好友 */}
          <div className="mt-3 bg-white">
            <button
              onClick={() => setShowDeleteDialog(true)}
              className="w-full px-4 py-3 text-center hover:bg-gray-50 transition-colors"
            >
              <span className="text-red-600">删除</span>
            </button>
          </div>
        </ScrollArea>

        {/* 删除好友确认对话框 */}
        <AlertDialog open={showDeleteDialog} onOpenChange={setShowDeleteDialog}>
          <AlertDialogContent className="max-w-[270px] rounded-xl p-0">
            <div className="pt-6 pb-4 px-6 text-center">
              <div className="mb-2">删除联系人</div>
              <div className="text-sm text-gray-500">
                将联系人"{contact.remark || contact.nickname}"删除，将同时删除与该联系人的聊天记录
              </div>
            </div>
            <div className="border-t border-gray-200 flex">
              <button
                onClick={() => setShowDeleteDialog(false)}
                className="flex-1 py-3 text-blue-600 border-r border-gray-200 hover:bg-gray-50 transition-colors"
              >
                取消
              </button>
              <button
                onClick={handleDeleteContact}
                className="flex-1 py-3 text-red-600 hover:bg-gray-50 transition-colors"
              >
                删除
              </button>
            </div>
          </AlertDialogContent>
        </AlertDialog>
      </div>
    );
  }

  return (
    <div className="fixed inset-0 bg-white z-[60] flex flex-col">
      {/* 顶部导航栏 */}
      <div className="flex items-center justify-between px-4 py-3 border-b bg-white">
        <button
          onClick={onClose}
          className="p-2 hover:bg-gray-100 rounded-full transition-colors"
        >
          <ArrowLeft className="w-6 h-6" />
        </button>
        <h1 className="text-lg">详细资料</h1>
        <button 
          onClick={() => setShowSettingsPage(true)}
          className="p-2 hover:bg-gray-100 rounded-full transition-colors"
        >
          <MoreHorizontal className="w-6 h-6" />
        </button>
      </div>

      {/* 主内容区域 */}
      <ScrollArea className="flex-1">
        <div className="pb-6">
          {/* 头像和基本信息区域 */}
          <div className="bg-white px-4 py-6">
            <div className="flex items-start gap-4">
              {/* 左侧头像 */}
              <Avatar className="w-16 h-16 shrink-0 rounded-md">
                <AvatarImage src={contact.avatar} />
                <AvatarFallback className="rounded-md">{contact.nickname[0]}</AvatarFallback>
              </Avatar>
              
              {/* 右侧信息 */}
              <div className="flex-1 min-w-0">
                {/* 备注名 - 加粗显示 */}
                <div className="mb-1">
                  <span className="text-xl font-bold">
                    {contact.remark || contact.nickname}
                  </span>
                </div>
                
                {/* 昵称 */}
                <div className="text-gray-500 mb-1">
                  <span className="text-sm">
                    昵称：{contact.nickname}
                  </span>
                </div>
                
                {/* AI给你的备注名 */}
                <div className={`mb-1 ${contact.userRemark ? 'text-purple-600' : 'text-gray-400'}`}>
                  <span className="text-sm">
                    Ta给你的备注：{contact.userRemark || '暂未设置'}
                  </span>
                </div>
                
                {/* 微信号 */}
                <div className="text-gray-500 mb-1">
                  <span className="text-sm">
                    微信号：{wechatId || contact.id}
                  </span>
                </div>
                
                {/* 地区 */}
                <div className="text-gray-500">
                  <span className="text-sm">
                    地区：{region || contact.location || '未设置'}
                  </span>
                </div>
              </div>
            </div>
            
            {/* 个性签名 */}
            <div className="mt-4 px-3 py-2 bg-gray-50 rounded-lg">
              <div className="text-sm text-gray-600 whitespace-pre-wrap">
                {signature || '这个人很神秘，什么都没有写'}
              </div>
            </div>
          </div>

          {/* 分隔线 */}
          <div className="h-2 bg-gray-100"></div>

          {/* AI设置 */}
          <div className="bg-white">
            <button 
              onClick={() => setShowAiSettings(true)}
              className="w-full px-4 py-3 flex items-center justify-between hover:bg-gray-50 transition-colors"
            >
              <div className="flex items-center gap-2">
                <Brain className="w-5 h-5 text-purple-600" />
                <span>AI设置</span>
              </div>
              <ChevronRight className="w-5 h-5 text-gray-400" />
            </button>
          </div>

          {/* 分隔线 */}
          <div className="h-2 bg-gray-100"></div>

          {/* 朋友资料 */}
          <div className="bg-white">
            <button 
              onClick={() => setShowProfileDetail(true)}
              className="w-full px-4 py-3 flex items-center justify-between hover:bg-gray-50 transition-colors"
            >
              <span>朋友资料</span>
              <ChevronRight className="w-5 h-5 text-gray-400" />
            </button>
          </div>

          {/* 分隔线 */}
          <div className="h-2 bg-gray-100"></div>

          {/* 朋友权限 */}
          <div className="bg-white">
            <button className="w-full px-4 py-3 flex items-center justify-between hover:bg-gray-50 transition-colors">
              <span>朋友权限</span>
              <ChevronRight className="w-5 h-5 text-gray-400" />
            </button>
            
            <div className="px-4 py-2 border-t border-gray-100">
              <div className="flex items-center justify-between py-2">
                <span className="text-sm text-gray-600">聊天、朋友圈、微信运动等</span>
              </div>
            </div>
          </div>

          {/* 分隔线 */}
          <div className="h-2 bg-gray-100"></div>

          {/* 朋友圈 */}
          <div className="bg-white">
            <button 
              onClick={onMomentsClick}
              className="w-full px-4 py-3 flex items-center justify-between hover:bg-gray-50 transition-colors"
            >
              <span>朋友圈</span>
              <div className="flex items-center gap-2">
                {moments.length > 0 && moments[0].images && moments[0].images.length > 0 && (
                  <div className="w-12 h-12 rounded overflow-hidden">
                    <img 
                      src={moments[0].images[0]} 
                      alt="" 
                      className="w-full h-full object-cover"
                    />
                  </div>
                )}
                <ChevronRight className="w-5 h-5 text-gray-400" />
              </div>
            </button>
          </div>

          {/* 底部操作按钮 */}
          <div className="px-4 py-4 space-y-2">
            <Button 
              className="w-full bg-green-500 hover:bg-green-600" 
              onClick={() => {
                onClose();
                if (onSendMessage) {
                  onSendMessage();
                }
              }}
            >
              发消息
            </Button>
            <Button 
              className="w-full" 
              variant="outline" 
              onClick={() => {
                onClose();
                if (onVideoCall) {
                  onVideoCall();
                }
              }}
            >
              音视频通话
            </Button>
          </div>
        </div>
      </ScrollArea>

      {/* 朋友资料详情对话框 */}
      <Dialog open={showProfileDetail} onOpenChange={setShowProfileDetail}>
        <DialogContent className="max-w-md max-h-[80vh] overflow-hidden flex flex-col">
          <DialogHeader>
            <DialogTitle>朋友资料</DialogTitle>
            <DialogDescription>
              查看 {contact.remark || contact.nickname} 的详细资料
            </DialogDescription>
          </DialogHeader>
          
          <ScrollArea className="flex-1 -mx-6 px-6">
            <div className="space-y-4 py-2">
              {/* 个性签名 */}
              {signature && (
                <div className="pb-4 border-b">
                  <div className="text-sm text-gray-500 mb-2">个性签名</div>
                  <div className="text-sm whitespace-pre-wrap bg-gray-50 p-3 rounded-lg">
                    {signature}
                  </div>
                </div>
              )}

              {/* 本名 */}
              {contact.realName && (
                <div className="pb-4 border-b">
                  <div className="text-sm text-gray-500 mb-2">本名</div>
                  <div className="text-sm">{contact.realName}</div>
                </div>
              )}
              
              {/* 年龄 */}
              {contact.age && (
                <div className="pb-4 border-b">
                  <div className="text-sm text-gray-500 mb-2">年龄</div>
                  <div className="text-sm">{contact.age}</div>
                </div>
              )}
              
              {/* 职业 */}
              {contact.occupation && (
                <div className="pb-4 border-b">
                  <div className="text-sm text-gray-500 mb-2">职业</div>
                  <div className="text-sm">{contact.occupation}</div>
                </div>
              )}
              
              {/* 性格 */}
              {contact.personality && (
                <div className="pb-4 border-b">
                  <div className="text-sm text-gray-500 mb-2">性格</div>
                  <div className="text-sm whitespace-pre-wrap">{contact.personality}</div>
                </div>
              )}
              
              {/* 兴趣爱好 */}
              {contact.hobbies && (
                <div className="pb-4 border-b">
                  <div className="text-sm text-gray-500 mb-2">兴趣爱好</div>
                  <div className="text-sm whitespace-pre-wrap">{contact.hobbies}</div>
                </div>
              )}

              {/* 共同群聊 */}
              {commonGroups.length > 0 && (
                <div>
                  <div className="text-sm text-gray-500 mb-2">
                    共同群聊 ({commonGroups.length})
                  </div>
                  <div className="space-y-2">
                    {commonGroups.map((group) => (
                      <div 
                        key={group.id}
                        className="flex items-center gap-3 p-3 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors cursor-pointer"
                      >
                        <div className="w-10 h-10 bg-gray-300 rounded-lg flex items-center justify-center">
                          <span className="text-sm">群</span>
                        </div>
                        <span className="text-sm flex-1">{group.name}</span>
                        <ChevronRight className="w-4 h-4 text-gray-400" />
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* 角色总结 */}
              {summaries && summaries.length > 0 && (
                <div className="pb-4 border-b">
                  <div className="flex items-center gap-2 mb-3">
                    <List className="w-4 h-4 text-purple-600" />
                    <div className="text-sm text-gray-500">
                      聊天总结 ({summaries.length})
                    </div>
                  </div>
                  <div className="space-y-3">
                    {summaries.slice().reverse().map((summary, index) => (
                      <div 
                        key={summary.id}
                        className="p-3 bg-gradient-to-br from-purple-50 to-blue-50 rounded-lg border border-purple-100"
                      >
                        <div className="flex items-center justify-between mb-2">
                          <span className="text-xs text-purple-600 font-medium">
                            总结 #{summaries.length - index}
                          </span>
                          <span className="text-xs text-gray-400">
                            {formatTime(summary.timestamp)}
                          </span>
                        </div>
                        <p className="text-sm text-gray-700 whitespace-pre-wrap leading-relaxed">
                          {summary.content}
                        </p>
                      </div>
                    ))}
                  </div>
                  <p className="text-xs text-gray-400 mt-3 text-center">
                    💡 这些是AI根据聊天记录生成的总结
                  </p>
                </div>
              )}
            </div>
          </ScrollArea>
        </DialogContent>
      </Dialog>

      {/* AI设置对话框 */}
      <Dialog open={showAiSettings} onOpenChange={setShowAiSettings}>
        <DialogContent className="max-w-md max-h-[85vh] overflow-hidden flex flex-col">
          <DialogHeader>
            <DialogTitle>AI设置</DialogTitle>
            <DialogDescription>
              配置 {contact.remark || contact.nickname} 的AI行为和记忆设置
            </DialogDescription>
          </DialogHeader>
          
          <ScrollArea className="flex-1 pr-4">
            <div className="space-y-6 py-2">
              {/* 上下文记忆条数 */}
              <div>
                <Label htmlFor="contextMemoryCount">上下文记忆条数</Label>
                <div className="flex items-center gap-3 mt-2">
                  <Input
                    id="contextMemoryCount"
                    type="number"
                    min="1"
                    max="100"
                    value={contextMemoryCount}
                    onChange={(e) => setContextMemoryCount(parseInt(e.target.value) || 10)}
                    className="w-24"
                  />
                  <span className="text-sm text-gray-600">条消息</span>
                </div>
                <p className="text-xs text-gray-500 mt-2">
                  AI可以看到最近的{contextMemoryCount}条聊天记录，数值越大，AI的记忆越长
                </p>
              </div>

              {/* 关联世界书 */}
              <div className="pb-4 border-b">
                <div className="flex items-center gap-2 mb-3">
                  <BookOpen className="w-4 h-4 text-blue-600" />
                  <Label>关联世界书</Label>
                </div>
                {worldBooks.length === 0 ? (
                  <p className="text-sm text-gray-400">暂无可用的世界书</p>
                ) : (
                  <div className="space-y-2">
                    {worldBooks.map((book) => (
                      <div
                        key={book.id}
                        className="flex items-start gap-3 p-3 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors"
                      >
                        <Checkbox
                          checked={selectedWorldBooks.includes(book.id)}
                          onCheckedChange={(checked) => {
                            if (checked) {
                              setSelectedWorldBooks([...selectedWorldBooks, book.id]);
                            } else {
                              setSelectedWorldBooks(selectedWorldBooks.filter(id => id !== book.id));
                            }
                          }}
                          className="mt-1"
                        />
                        <div className="flex-1 min-w-0">
                          <div className="font-medium text-sm mb-1">{book.name}</div>
                          {book.description && (
                            <p className="text-xs text-gray-500">{book.description}</p>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                )}
                <p className="text-xs text-gray-500 mt-3">
                  已选择 {selectedWorldBooks.length} 个世界书。AI会在回复时参考这些背景设定和世界观。
                </p>
              </div>

              {/* 关联规则 */}
              <div className="pb-4 border-b">
                <div className="flex items-center gap-2 mb-3">
                  <FileText className="w-4 h-4 text-blue-600" />
                  <Label>关联规则</Label>
                </div>
                {rules.length === 0 ? (
                  <p className="text-sm text-gray-400">暂无可用的规则</p>
                ) : (
                  <div className="space-y-2">
                    {rules.map((rule) => (
                      <div
                        key={rule.id}
                        className="flex items-start gap-3 p-3 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors"
                      >
                        <Checkbox
                          checked={selectedRules.includes(rule.id)}
                          onCheckedChange={(checked) => {
                            if (checked) {
                              setSelectedRules([...selectedRules, rule.id]);
                            } else {
                              setSelectedRules(selectedRules.filter(id => id !== rule.id));
                            }
                          }}
                          className="mt-1"
                        />
                        <div className="flex-1 min-w-0">
                          <div className="font-medium text-sm mb-1">{rule.name}</div>
                          {rule.description && (
                            <p className="text-xs text-gray-500">{rule.description}</p>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                )}
                <p className="text-xs text-gray-500 mt-3">
                  已选择 {selectedRules.length} 个规则。AI会在回复时参考这些规则。
                </p>
              </div>

              {/* 头像库管理 */}
              <div className="pb-4 border-b">
                <div className="flex items-center justify-between mb-3">
                  <div className="flex items-center gap-2">
                    <ImagePlus className="w-4 h-4 text-blue-600" />
                    <Label>角色头像库</Label>
                  </div>
                  <Button
                    type="button"
                    size="sm"
                    variant="outline"
                    onClick={() => setShowAvatarLibrary(true)}
                  >
                    管理头像
                  </Button>
                </div>
                <p className="text-xs text-gray-500">
                  为角色上传多个头像，AI会根据情绪和场景自动切换头像（当前头像数：{avatarLibrary.length}）
                </p>
              </div>
            </div>
          </ScrollArea>

          <div className="flex gap-2 pt-4 border-t">
            <Button
              type="button"
              variant="outline"
              onClick={() => {
                // 恢复到原始值
                setContextMemoryCount(contact.contextMemoryCount || 10);
                setSelectedWorldBooks(contact.worldBooks || []);
                setSelectedRules(contact.rules || []);
                setAvatarLibrary(contact.avatarLibrary || []);
                setShowAiSettings(false);
              }}
              className="flex-1"
            >
              取消
            </Button>
            <Button
              type="button"
              onClick={() => {
                if (onContactUpdate) {
                  onContactUpdate({
                    ...contact,
                    contextMemoryCount,
                    worldBooks: selectedWorldBooks,
                    rules: selectedRules,
                    avatarLibrary
                  });
                }
                toast.success('AI设置已保存');
                setShowAiSettings(false);
              }}
              className="flex-1"
            >
              保存
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      {/* 头像库管理对话框 */}
      <Dialog open={showAvatarLibrary} onOpenChange={setShowAvatarLibrary}>
        <DialogContent className="max-w-md max-h-[85vh] overflow-hidden flex flex-col">
          <DialogHeader>
            <DialogTitle>角色头像库</DialogTitle>
            <DialogDescription>
              为 {contact.remark || contact.nickname} 添加多个头像，AI会根据情绪和场景自动切换
            </DialogDescription>
          </DialogHeader>
          
          <ScrollArea className="flex-1 pr-4">
            <div className="space-y-4 py-2">
              {/* 当前头像展示 */}
              <div className="pb-4 border-b">
                <div className="text-sm text-gray-500 mb-3">当前使用的头像</div>
                <div className="flex items-center gap-3 p-3 bg-gray-50 rounded-lg">
                  <Avatar className="w-16 h-16">
                    <AvatarImage src={contact.avatar} />
                    <AvatarFallback>{contact.nickname[0]}</AvatarFallback>
                  </Avatar>
                  <div className="flex-1">
                    <div className="text-sm">默认头像</div>
                    <div className="text-xs text-gray-500 mt-1">在角色详细资料中设置</div>
                  </div>
                </div>
              </div>

              {/* 头像库列表 */}
              <div>
                <div className="flex items-center justify-between mb-3">
                  <div className="text-sm text-gray-500">
                    头像库 ({avatarLibrary.length})
                  </div>
                  <Button
                    type="button"
                    size="sm"
                    onClick={() => setShowAddAvatar(true)}
                  >
                    <ImagePlus className="w-4 h-4 mr-1" />
                    添加头像
                  </Button>
                </div>

                {avatarLibrary.length === 0 ? (
                  <div className="text-center py-8 text-gray-400">
                    <ImagePlus className="w-12 h-12 mx-auto mb-2 opacity-50" />
                    <p>还没有添加头像</p>
                    <p className="text-xs mt-1">点击"添加头像"开始创建头像库</p>
                  </div>
                ) : (
                  <div className="space-y-2">
                    {avatarLibrary.map((avatar) => (
                      <div
                        key={avatar.id}
                        className="flex items-start gap-3 p-3 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors relative group"
                      >
                        {/* 头像 */}
                        <div className="w-16 h-16 shrink-0 rounded overflow-hidden">
                          <ImageWithFallback
                            src={avatar.url}
                            alt={avatar.emotion}
                            className="w-full h-full object-cover"
                          />
                        </div>

                        {/* 信息 */}
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-2 mb-1">
                            <span className="inline-block px-2 py-0.5 bg-blue-100 text-blue-700 text-xs rounded">
                              {avatar.emotion}
                            </span>
                          </div>
                          <p className="text-xs text-gray-600 whitespace-pre-wrap">
                            {avatar.description}
                          </p>
                        </div>

                        {/* 删除按钮 */}
                        <button
                          onClick={() => handleDeleteAvatar(avatar.id)}
                          className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity p-1 bg-red-500 text-white rounded-full hover:bg-red-600"
                        >
                          <XIcon className="w-4 h-4" />
                        </button>
                      </div>
                    ))}
                  </div>
                )}

                {avatarLibrary.length > 0 && (
                  <div className="mt-4 p-3 bg-blue-50 rounded-lg">
                    <div className="text-xs text-blue-900">
                      💡 <strong>使用提示：</strong>
                    </div>
                    <ul className="text-xs text-blue-800 mt-2 space-y-1 ml-4 list-disc">
                      <li>AI会根据当前情绪和场景选择合适的头像</li>
                      <li>头像切换不会很频繁，只在明显的情绪变化时</li>
                      <li>描述越详细，AI越能准确判断何时使用该头像</li>
                      <li>例如："开心笑着"、"生气皱眉"、"难过哭泣"等</li>
                    </ul>
                  </div>
                )}
              </div>
            </div>
          </ScrollArea>

          <div className="flex gap-2 pt-4 border-t">
            <Button
              type="button"
              variant="outline"
              onClick={() => {
                setAvatarLibrary(contact.avatarLibrary || []);
                setShowAvatarLibrary(false);
              }}
              className="flex-1"
            >
              取消
            </Button>
            <Button
              type="button"
              onClick={handleSaveAvatarLibrary}
              className="flex-1"
            >
              保存
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      {/* 添加头像对话框 */}
      <Dialog open={showAddAvatar} onOpenChange={(open) => {
        setShowAddAvatar(open);
        if (!open) {
          setNewAvatar({ url: '', emotion: '', description: '' });
          setAvatarLocalFile(null);
          setAvatarLocalPreview('');
          setAvatarUploadMethod('url');
        }
      }}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>添加头像</DialogTitle>
            <DialogDescription>
              为角色添加新的表情头像
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4 py-4">
            {/* 上传方式选择 */}
            <div className="flex gap-2">
              <Button
                type="button"
                variant={avatarUploadMethod === 'url' ? 'default' : 'outline'}
                size="sm"
                onClick={() => setAvatarUploadMethod('url')}
                className="flex-1"
              >
                <Link2 className="w-4 h-4 mr-2" />
                URL链接
              </Button>
              <Button
                type="button"
                variant={avatarUploadMethod === 'upload' ? 'default' : 'outline'}
                size="sm"
                onClick={() => setAvatarUploadMethod('upload')}
                className="flex-1"
              >
                <Upload className="w-4 h-4 mr-2" />
                本地上传
              </Button>
            </div>

            {/* URL输入 */}
            {avatarUploadMethod === 'url' && (
              <div>
                <Label>头像URL</Label>
                <Input
                  value={newAvatar.url}
                  onChange={(e) => setNewAvatar({ ...newAvatar, url: e.target.value })}
                  placeholder="https://example.com/avatar.png"
                  className="mt-2"
                />
              </div>
            )}

            {/* 本地上传 */}
            {avatarUploadMethod === 'upload' && (
              <div>
                <Label>选择图片</Label>
                <div className="mt-2">
                  <input
                    type="file"
                    accept="image/*"
                    onChange={handleAvatarFileUpload}
                    className="hidden"
                    id="avatar-file-upload"
                  />
                  <label
                    htmlFor="avatar-file-upload"
                    className="flex flex-col items-center justify-center border-2 border-dashed border-gray-300 rounded-lg p-6 cursor-pointer hover:border-gray-400 transition-colors"
                  >
                    {avatarLocalPreview ? (
                      <div className="flex flex-col items-center gap-2">
                        <ImageWithFallback
                          src={avatarLocalPreview}
                          alt="预览"
                          className="w-24 h-24 object-cover rounded"
                        />
                        <p className="text-sm text-gray-500">点击重新选择</p>
                      </div>
                    ) : (
                      <>
                        <Upload className="w-8 h-8 text-gray-400 mb-2" />
                        <span className="text-sm text-gray-500">点击选择图片（最大5MB）</span>
                      </>
                    )}
                  </label>
                </div>
              </div>
            )}

            {/* 情绪/场景标签 */}
            <div>
              <Label>情绪/场景标签</Label>
              <Input
                value={newAvatar.emotion}
                onChange={(e) => setNewAvatar({ ...newAvatar, emotion: e.target.value })}
                placeholder="例如：开心、生气、难过、默认"
                className="mt-2"
              />
              <p className="text-xs text-gray-500 mt-1">
                简短的标签，表示这个头像适用的情绪或场景
              </p>
            </div>

            {/* 详细描述 */}
            <div>
              <Label>详细描述</Label>
              <Textarea
                value={newAvatar.description}
                onChange={(e) => setNewAvatar({ ...newAvatar, description: e.target.value })}
                placeholder="详细描述这个头像的表情、情绪和适用场景，帮助AI判断何时使用。例如：笑得很开心，眼睛弯成月牙，适合在收到礼物、被夸奖、心情愉悦的时候使用"
                rows={4}
                className="mt-2"
              />
              <p className="text-xs text-gray-500 mt-1">
                描述越详细，AI越能准确判断何时使用该头像
              </p>
            </div>
          </div>

          <div className="flex gap-2 pt-4 border-t">
            <Button
              type="button"
              variant="outline"
              onClick={() => setShowAddAvatar(false)}
              className="flex-1"
            >
              取消
            </Button>
            <Button
              type="button"
              onClick={handleAddAvatarToLibrary}
              className="flex-1"
            >
              添加
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}